/**
 * Central route registry for authenticated app pages.
 * Use these constants instead of hardcoded path strings.
 */
export const routes = {
    home: '/dashboard',
    onboarding: '/dashboard/onboarding',
    profile: '/profile',
    selectAccount: '/select-account',

    sales: {
        root: '/sales',
        list: '/sales/list',
        new: '/sales/new',
        detail: (id: string) => `/sales/${id}` as const,
        invoice: (id: string) => `/sales/${id}/invoice` as const,
        pos: '/sales/pos',
        customerPayments: '/sales/customer-payments',
        customerLedger: '/sales/customer-ledger',
        delivery: '/sales/delivery',
        returns: '/sales/returns',
        returnNew: '/sales/returns/new',
        returnDetail: (id: string) => `/sales/returns/${id}` as const,
        orders: '/sales/orders',
        orderNew: '/sales/orders/new',
        orderDetail: (id: string) => `/sales/orders/${id}` as const,
        quotes: '/sales/quotes',
        quoteNew: '/sales/quotes/new',
        quoteDetail: (id: string) => `/sales/quotes/${id}` as const,
        warrantyClaims: '/sales/warranty-claims',
        cashierSessions: '/sales/cashier-sessions',
        loyalty: '/sales/loyalty',
        crm: {
            followUps: '/crm/follow-ups',
            campaigns: '/crm/campaigns',
        },
        customers: '/sales/customers',
        customerDetail: (id: string) => `/sales/customers/${id}` as const,
        customerHistory: (id: string) => `/sales/customers/${id}/history` as const,
        customerDueAging: '/sales/customers/reports/due-aging',
        customerGroups: '/sales/customer-groups',
        priceLists: '/sales/price-lists',
        priceListDetail: (id: string) => `/sales/price-lists/${id}` as const,
        territories: '/sales/territories',
        reports: {
            summary: '/sales/reports/summary',
            products: '/sales/reports/products',
            monthly: '/sales/reports/monthly',
            customers: '/sales/reports/customers',
            consolidated: '/sales/reports/consolidated',
            branchReport: '/sales/reports/branch-report',
            grossProfit: '/sales/reports/gross-profit',
            grossProfitExceptions: '/sales/reports/gross-profit/exceptions',
            grossProfitSalespeople: '/sales/reports/gross-profit/salespeople',
            grossProfitBridge: '/sales/reports/gross-profit/bridge',
        },
    },

    purchases: {
        root: '/purchases',
        list: '/purchases/list',
        purchaseDetail: (id: string) => `/purchases/${id}` as const,
        purchaseInvoice: (id: string) => `/purchases/${id}/invoice` as const,
        supplierPayments: '/purchases/supplier-payments',
        supplierLedger: '/purchases/supplier-ledger',
        orders: '/purchases/orders',
        orderDetail: (id: string) => `/purchases/orders/${id}` as const,
        orderInvoice: (id: string) => `/purchases/orders/${id}/invoice` as const,
        quotations: '/purchases/quotations',
        quotationDetail: (id: string) => `/purchases/quotations/${id}` as const,
        returns: '/purchases/returns',
        returnDetail: (id: string) => `/purchases/returns/${id}` as const,
        suppliers: '/purchases/suppliers',
        imports: {
            root: '/purchases/imports',
            shipmentNew: '/purchases/imports/new',
            shipmentDetail: (id: string) => `/purchases/imports/${id}` as const,
            lcRegister: '/purchases/imports/lc-register',
            dutyReport: '/purchases/imports/duty-report',
        },
        reports: {
            summary: '/purchases/reports/summary',
            byProduct: '/purchases/reports/by-product',
            bySupplier: '/purchases/reports/by-supplier',
        },
    },

    accounting: {
        root: '/accounting',
        vouchers: '/accounting/vouchers',
        voucherEntry: '/accounting/vouchers/new',
        voucherDetail: (id: string) => `/accounting/vouchers/${id}` as const,
        journal: '/accounting/journal',
        journalDetail: (id: string) => `/accounting/vouchers/${id}` as const,
        ledger: '/accounting/ledger',
        reconciliation: '/accounting/reconciliation',
        reconciliationBank: '/accounting/reconciliation/bank',
        coa: '/accounting/coa',
        accountGroups: '/accounting/account-groups',
        postingRules: '/accounting/posting-rules',
        costCenters: '/accounting/cost-centers',
        fiscalPeriods: '/accounting/fiscal-periods',
        settings: '/accounting/settings',
        approvalQueue: '/accounting/vouchers?approvalStatus=PENDING',
        fixedAssets: '/accounting/fixed-assets',
        openingBalances: '/accounting/opening-balances',
        recurringJournals: '/accounting/recurring-journals',
        recurringVouchers: '/accounting/recurring-vouchers',
        voucherTemplates: '/accounting/voucher-templates',
        expenses: '/accounting/expenses',
        expenseCategories: '/accounting/expenses/categories',
        expenseReports: '/accounting/expenses/reports',
        loans: '/accounting/loans',
        investors: '/accounting/investors',
        interBranchFundTransfers: '/accounting/inter-branch/fund-transfers',
        reports: {
            pl: '/accounting/reports/pl',
            balanceSheet: '/accounting/reports/balance-sheet',
            cashbook: '/accounting/reports/cashbook',
            bankbook: '/accounting/reports/bankbook',
            trialBalance: '/accounting/reports/trial-balance',
            arAging: '/accounting/reports/ar-aging',
            apAging: '/accounting/reports/ap-aging',
            cashFlow: '/accounting/reports/cash-flow',
            vatTax: '/accounting/reports/vat-tax',
            comparativePl: '/accounting/reports/comparative-pl',
            budgetVsActual: '/accounting/reports/budget-vs-actual',
            financialRatios: '/accounting/reports/financial-ratios',
        },
    },

    inventory: {
        root: '/inventory',
        products: '/inventory/products',
        demands: '/inventory/demands',
        transfers: '/inventory/transfers',
        transferDetail: (id: string) => `/inventory/transfers/${id}` as const,
        shrinkage: '/inventory/shrinkage',
        stockTakes: '/inventory/stock-takes',
        stockTakeDetail: (id: string) => `/inventory/stock-takes/${id}` as const,
        labels: '/inventory/labels',
        ledger: '/inventory/ledger',
        categories: '/inventory/categories',
        settings: '/inventory/settings',
        brands: '/inventory/brands',
        reports: {
            reorder: '/inventory/reports/reorder',
            shrinkage: '/inventory/reports/shrinkage',
            valuation: '/inventory/reports/valuation',
            stockOnHand: '/inventory/reports/stock-on-hand',
        },
    },

    crm: {
        root: '/crm',
        customers: '/crm/customers',
        leads: '/crm/leads',
        leadNew: '/crm/leads/new' as const,
        leadDetail: (id: string) => `/crm/leads/${id}` as const,
        contacts: '/crm/contacts',
        contactNew: '/crm/contacts/new' as const,
        contactDetail: (id: string) => `/crm/contacts/${id}` as const,
        activities: '/crm/activities',
        // Both superseded by `activities` in R2; the pages redirect there and the
        // routes stay so old bookmarks and saved sidebar layouts keep resolving.
        conversations: '/crm/conversations',
        followUps: '/crm/follow-ups',
        campaigns: '/crm/campaigns',
        setup: '/crm/setup',
        // The two old single-list settings pages. Both now redirect into the tabs
        // of /crm/setup; kept as constants so nothing has to hardcode a stale path.
        customFields: '/crm/settings/custom-fields',
        leadTaxonomy: '/crm/settings/lead-taxonomy',
    },

    projects: {
        root: '/projects',
        new: '/projects/new' as const,
        detail: (id: string) => `/projects/${id}` as const,
        boards: '/projects/boards',
        boardDetail: (id: string) => `/projects/boards/${id}` as const,
        boardColumns: (id: string) => `/projects/boards/${id}/columns` as const,
        columns: (id: string) => `/projects/${id}/columns` as const,
        edit: (id: string) => `/projects/${id}/edit` as const,
        tasks: '/projects/tasks',
        sprints: '/projects/sprints',
        sprintDetail: (id: string) => `/projects/sprints/${id}` as const,
        hourLogs: '/projects/hour-logs',
        hourLogReport: '/projects/hour-logs/report',
        settings: '/projects/settings',
    },

    hr: {
        root: '/hr',
        employees: '/hr/employees',
        employeeDetail: (id: string) => `/hr/employees/${id}` as const,
        departments: '/hr/employees/departments',
        designations: '/hr/employees/designations',
        attendance: '/hr/attendance',
        attendancePunches: '/hr/attendance/punches',
        schedules: '/hr/schedules',
        leaves: '/hr/leaves',
        salaryPayments: '/hr/salary-payments',
        jobPosts: '/hr/recruitment/job-posts',
        jobPostDetail: (id: string) => `/hr/recruitment/job-posts/${id}` as const,
        applicants: '/hr/recruitment/applicants',
        applications: '/hr/recruitment/applications',
        reports: {
            attendance: '/hr/reports/attendance',
            leaveBalance: '/hr/reports/leave-balance',
            payrollCost: '/hr/reports/payroll-cost',
            wagesRegister: '/hr/reports/wages-register',
            employeeRegister: '/hr/reports/employee-register',
            taxDeduction: '/hr/reports/tax-deduction',
            providentFund: '/hr/reports/provident-fund',
            serviceBook: '/hr/reports/service-book',
        },
    },

    /**
     * The careers surface. Outside `(app)` — these pages are served to job
     * seekers who hold no ERP session, so they must not depend on the app
     * shell, the tenant header, or `access_token`.
     */
    careers: {
        root: '/careers',
        jobDetail: (id: string) => `/careers/jobs/${id}` as const,
        login: '/careers/login',
        register: '/careers/register',
        portal: '/careers/portal',
        profile: '/careers/portal/profile',
        applicationDetail: (id: string) => `/careers/portal/applications/${id}` as const,
    },

    storefront: {
        root: '/storefront',
        settings: '/storefront/settings',
    },

    settings: {
        root: '/settings',
        branding: '/settings/branding',
        tax: '/settings/tax',
        auditLogs: '/settings/audit-logs',
        loyalty: '/settings/loyalty',
        sms: '/settings/sms',
        reports: '/settings/reports',
        discountCodes: '/settings/discount-codes',
        urlShortener: '/settings/url-shortener',
        paymentMethods: '/settings/payment-methods',
        sales: '/settings/sales',
        printTemplates: '/settings/print-templates',
        team: '/team',
        counters: '/settings/counters',
        localization: '/settings/localization',
        dashboard: '/settings/dashboard',
        data: '/settings/data',
        stores: '/settings/stores',
    },

    admin: {
        root: '/admin',
        tenants: '/admin/tenants',
        tenantPayments: '/admin/tenants/payments',
        tenantLedger: '/admin/tenants/ledger',
        users: '/admin/users',
        referrals: '/admin/referrals',
        urlShortener: '/admin/url-shortener',
        socialMedia: '/admin/social-media',
        feedback: '/admin/feedback',
        support: '/admin/support',
        systemHealth: '/admin/system-health',
        platformSettings: {
            root: '/admin/platform-settings',
            general: '/admin/platform-settings/general',
            tenantFeatures: '/admin/platform-settings/tenant-features',
            email: '/admin/platform-settings/email',
            sms: '/admin/platform-settings/sms',
            whatsapp: '/admin/platform-settings/whatsapp',
            payments: '/admin/platform-settings/payments',
            ai: '/admin/platform-settings/ai',
            navigation: '/admin/platform-settings/navigation',
            plans: '/admin/platform-settings/plans',
            addons: '/admin/platform-settings/addons',
            buffer: '/admin/platform-settings/buffer',
            feedbackAutomation: '/admin/platform-settings/feedback-automation',
            deploy: '/admin/platform-settings/deploy',
        },
    },

    referralsPortal: {
        root: '/referrals',
        signups: '/referrals/signups',
        payments: '/referrals/payments',
    },

    /**
     * Employee self-service. Short path because employees type it. One route
     * with tabs rather than four — this is a phone screen and a tab strip beats
     * a back button for four small views.
     */
    employeePortal: {
        root: '/my',
    },
    billing: '/billing',
    team: '/team',
    help: '/help',
    status: '/status',
    support: '/support',
    smsCredits: '/sms-credits',
    aiCredits: '/ai-credits',
    manufacturing: '/manufacturing',
} as const;