-- AlterTable
ALTER TABLE "User"
	ADD COLUMN IF NOT EXISTS "token_version" INTEGER NOT NULL DEFAULT 0,
	ADD COLUMN IF NOT EXISTS "email_verified_at" TIMESTAMP(3),
	ADD COLUMN IF NOT EXISTS "totp_secret" TEXT;
