/**
 * Text normalization shared by every matcher.
 *
 * Bangladeshi retail data arrives in two scripts and two digit systems, so a
 * comparison that does not normalize first will treat "নাপা ৫০০" and "Napa 500"
 * as unrelated — and, worse, treat the same Bengali word typed in composed and
 * decomposed form as two different suppliers.
 */

const BENGALI_ZERO = 0x09e6;

/** Bengali ০-৯ to ASCII 0-9. */
export function normalizeDigits(raw: string): string {
    return raw.replace(/[০-৯]/g, (d) => String(d.charCodeAt(0) - BENGALI_ZERO));
}

/** Case-folded, NFC, ASCII-digit, punctuation-free, single-spaced. */
export function normalizeName(raw: string): string {
    if (!raw) return '';
    return normalizeDigits(raw.normalize('NFC'))
        .toLowerCase()
        // Keep letters (any script), digits and spaces; punctuation becomes a
        // space so "Napa-500" and "Napa 500" agree.
        //
        // `\p{M}` is not optional: Bengali vowel signs are non-spacing marks,
        // not letters, so dropping them turns "নাপা" into "ন প" — which would
        // then match any other consonant-skeleton name. Keeping marks is what
        // makes Bengali names comparable at all.
        .replace(/[^\p{L}\p{N}\p{M}]+/gu, ' ')
        .trim()
        .replace(/\s+/g, ' ');
}

/**
 * Suffixes that carry no identity — two suppliers differing only by "Ltd" are
 * one supplier. Ordered longest-first so "private limited" is consumed before
 * "limited" alone.
 */
const COMPANY_SUFFIXES = [
    'private limited',
    'pvt ltd',
    'and sons',
    'enterprises',
    'enterprise',
    'agencies',
    'company',
    'limited',
    'traders',
    'trading',
    'agency',
    'sons',
    'corp',
    'inc',
    'ltd',
    'co',
];

/** `normalizeName` plus trailing corporate suffixes removed. */
export function normalizeCompanyName(raw: string): string {
    let name = normalizeName(raw);
    let changed = true;

    while (changed) {
        changed = false;
        for (const suffix of COMPANY_SUFFIXES) {
            if (name.endsWith(` ${suffix}`)) {
                const stripped = name.slice(0, -(suffix.length + 1)).trim();
                // Never strip the name down to nothing: a supplier literally
                // called "Traders" keeps its name.
                if (stripped) {
                    name = stripped;
                    changed = true;
                }
            }
        }
    }

    return name;
}

/**
 * Bangladeshi mobile numbers to `+8801XXXXXXXXX`.
 *
 * Phone is the only real identity a customer carries — the customer *code* is
 * generated by the provider from its own row id, so it is not identity at all.
 */
export function normalizePhone(raw: string | null): string | null {
    if (!raw) return null;

    const digits = normalizeDigits(raw.normalize('NFC')).replace(/\D/g, '');
    if (!digits) return null;

    let local: string;
    if (digits.startsWith('880')) local = digits.slice(3);
    else if (digits.startsWith('0')) local = digits.slice(1);
    else local = digits;

    // A BD mobile is 1 followed by 9 digits once the country/trunk prefix is off.
    if (!/^1\d{9}$/.test(local)) return null;
    return `+880${local}`;
}
